services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development  # Ensure we're using the right stage
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development

  storybook:
    build:
      context: .
      dockerfile: Dockerfile.storybook
    ports:
      - "6006:6006"
    command: npm run storybook
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development